### ISSUE TITLE
Sometimes the bot loops

### ISSUE THREAD

**Issue by Demomute** [123hotdog1100/DemoMutebot#4]
Sometimes the bot will loop and be unable to find out if i am live

**Comment by 123hotdog1100** [comment]
Waiting for the bug to happen again so i can get the log

**Comment by 123hotdog1100** [comment]
![image](https://user-images.githubusercontent.com/14129417/121757201-b1573900-cb14-11eb-9c2f-cc5bf22690c0.png)
Quick work arround will be to just introduct a try and except statement to it

**Comment by 123hotdog1100** [comment]
Should be fixed in the commit [https://github.com/123hotdog1100/DemoMutebot/commit/f60aaab7456875d5a30ae68054c068e661d1fc12](url)
